const dummy = [
  {
    "id": 31640,
    "movie_id": 4584,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 114388,
    "overview": "Rich Mr. Dashwood dies, leaving his second wife and her daughters poor by the rules of inheritance. Two daughters are the titular opposites.",
    "popularity": "10.673167",
    "score": 7.7,
    "title": "Sense and Sensibility (1995)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzk1MjU3MDQyMl5BMl5BanBnXkFtZTcwNjc1OTM2MQ@@._V1_UX182_CR0",
    "keywords": "[{'id': 420, 'name': 'bowling'}, {'id': 818, 'name': 'based on novel'}, {'id': 964, 'name': 'servant'}, {'id': 2755, 'name': 'country life'}, {'id': 7564, 'name': 'jane austen'}, {'id': 10911, 'name': 'inheritance'}, {'id': 11109, 'name': 'military officer'}, {'id': 15060, 'name': 'period drama'}, {'id': 156507, 'name': 'rainstorm'}, {'id': 156510, 'name': 'horse and carriage'}, {'id': 156512, 'name': 'decorum'}]"
  },
  {
    "id": 31658,
    "movie_id": 687,
    "genres": "[{'id': 18, 'name': 'Drama'}]",
    "imdb_id": 112818,
    "overview": "A justice drama based on a true story about a man on death row who in his last days forms a strong relationship with a nun who teaches him forgiveness and gives him spirituality as she accompanies him to his execution. Susan Sarandon won an Oscar for best female actress for her convincing portrayal of Sister Helen Prejean.",
    "popularity": "6.891317",
    "score": 7.6,
    "title": "Dead Man Walking (1995)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM3NzA1MjM2N15BMl5BanBnXkFtZTcwMzY3MTMzNA@@._V1_UX182_CR0",
    "keywords": "[{'id': 378, 'name': 'prison'}, {'id': 570, 'name': 'rape'}, {'id': 1952, 'name': 'socially deprived family'}, {'id': 2060, 'name': 'penalty'}, {'id': 2122, 'name': 'death penalty'}, {'id': 2300, 'name': 'despair'}, {'id': 2501, 'name': 'death row'}, {'id': 2538, 'name': 'begnadigung'}, {'id': 2726, 'name': 'therapist'}, {'id': 2796, 'name': 'self-discovery'}, {'id': 2885, 'name': 'prison cell'}, {'id': 3012, 'name': 'court case'}, {'id': 3437, 'name': 'death sentence'}, {'id': 3440, 'name': 'doomed man'}, {'id': 3441, 'name': 'sentence'}, {'id': 3442, 'name': 'lethal injection'}, {'id': 3446, 'name': 'forgiveness'}, {'id': 3447, 'name': 'charity'}, {'id': 3448, 'name': 'mercy petition'}, {'id': 3927, 'name': 'rage and hate'}, {'id': 6059, 'name': 'unsociability'}, {'id': 6145, 'name': 'right and justice'}, {'id': 6148, 'name': 'court'}, {'id': 11263, 'name': 'electric chair'}, {'id': 13001, 'name': 'cowardliness'}]"
  },
  {
    "id": 31668,
    "movie_id": 807,
    "genres": "[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 114369,
    "overview": "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the \"seven deadly sins\" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer's mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.",
    "popularity": "18.45743",
    "score": 8.6,
    "title": "Se7en (1995)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0",
    "keywords": "[{'id': 476, 'name': 'self-fulfilling prophecy'}, {'id': 703, 'name': 'detective'}, {'id': 1470, 'name': 's.w.a.t.'}, {'id': 2231, 'name': 'drug dealer'}, {'id': 3597, 'name': 'evisceration'}, {'id': 3857, 'name': 'lust and impulsiveness'}, {'id': 3927, 'name': 'rage and hate'}, {'id': 3932, 'name': 'pride and vanity'}, {'id': 4138, 'name': 'immoderateness'}, {'id': 4142, 'name': 'insomnia'}, {'id': 5340, 'name': 'investigation'}, {'id': 6125, 'name': 'pension'}, {'id': 6149, 'name': 'police'}, {'id': 10714, 'name': 'serial killer'}]"
  },
  {
    "id": 31672,
    "movie_id": 11448,
    "genres": "[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 113819,
    "overview": "When Lenny and his wife, Amanda, adopt a baby, Lenny realizes that his son is a genius and becomes obsessed with finding the boy's biological mother in hopes that she will be brilliant too. But when he learns that Max's mother is Linda Ash, a kindhearted prostitute and porn star, Lenny is determined to reform her immoral lifestyle. A Greek chorus chimes in to relate the plot to Greek mythology in this quirky comedy.",
    "popularity": "15.899134",
    "score": 7.1,
    "title": "Mighty Aphrodite (1995)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMGM1NzM2ZjktNDM5ZS00YmExLTk5ZmYtNDdkNjdkNTdhZWZkXkEyXkFqcGdeQXVyNjE5MjUyOTM@._V1_UX182_CR0",
    "keywords": "[{'id': 549, 'name': 'prostitute'}, {'id': 2393, 'name': 'adoption'}, {'id': 4130, 'name': 'adoptive father'}, {'id': 5885, 'name': 'childlessness'}, {'id': 6230, 'name': 'looking for  birth parents'}, {'id': 8018, 'name': 'adoptive mother'}, {'id': 10183, 'name': 'independent film'}, {'id': 33625, 'name': 'illegal prostitution'}, {'id': 208349, 'name': 'child'}]"
  },
  {
    "id": 31756,
    "movie_id": 649,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 61395,
    "overview": "Beautiful young housewife Séverine Serizy cannot reconcile her masochistic fantasies with her everyday life alongside dutiful husband Pierre. When her lovestruck friend Henri mentions a secretive high-class brothel run by Madame Anais, Séverine begins to work there during the day under the name Belle de Jour. But when one of her clients grows possessive, she must try to go back to her normal life.",
    "popularity": "10.142662",
    "score": 7.8,
    "title": "Belle de Jour (1967)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjhjYWVjZWItZmE3OS00ZTNmLWJhYTktZGM1YWZiNDgxNTU2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR4",
    "keywords": "[{'id': 549, 'name': 'prostitute'}, {'id': 596, 'name': 'adultery'}, {'id': 848, 'name': 'double life'}, {'id': 851, 'name': 'dual identity'}, {'id': 931, 'name': 'jealousy'}, {'id': 1157, 'name': 'wife husband relationship'}, {'id': 1411, 'name': 'brothel'}, {'id': 1566, 'name': 'dream'}, {'id': 2316, 'name': \"women's sexual identity\"}, {'id': 2486, 'name': 'fantasy'}, {'id': 3260, 'name': 'masochism'}, {'id': 10183, 'name': 'independent film'}]"
  },
  {
    "id": 31762,
    "movie_id": 8963,
    "genres": "[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}]",
    "imdb_id": 112740,
    "overview": "On a US nuclear missile sub, a young first officer stages a mutiny to prevent his trigger happy captain from launching his missiles before confirming his orders to do so.",
    "popularity": "8.657365",
    "score": 7.3,
    "title": "Crimson Tide (1995)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMmFkY2IxNTAtMWRiNS00MWU2LWI1NDYtY2YxYTQyYTk5OTBhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0",
    "keywords": "[{'id': 339, 'name': 'submarine'}, {'id': 1860, 'name': 'mutiny'}, {'id': 2139, 'name': 'russia'}, {'id': 2534, 'name': 'missile'}, {'id': 3312, 'name': 'nuclear missile'}, {'id': 4123, 'name': 'embassy'}, {'id': 4410, 'name': 'u.s. navy'}, {'id': 4933, 'name': 'battle for power'}, {'id': 6791, 'name': 'torpedo'}, {'id': 162365, 'name': 'military'}, {'id': 198423, 'name': 'moral dilemma'}, {'id': 217133, 'name': 'post cold war'}, {'id': 221092, 'name': 'aircraft carrier'}, {'id': 226740, 'name': 'chain of command'}, {'id': 226741, 'name': 'launch code'}, {'id': 226742, 'name': 'sonar'}]"
  },
  {
    "id": 31818,
    "movie_id": 2292,
    "genres": "[{'id': 35, 'name': 'Comedy'}]",
    "imdb_id": 109445,
    "overview": "Convenience and video store clerks Dante and Randal are sharp-witted, potty-mouthed and bored out of their minds. So in between needling customers, the counter jockeys play hockey on the roof, visit a funeral home and deal with their love lives.",
    "popularity": "10.513367",
    "score": 7.8,
    "title": "Clerks (1994)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzE1Njk0NmItNDhlMC00ZmFlLWI4ZTUtYTY4ZjgzNjkyMTU1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0",
    "keywords": "[{'id': 1361, 'name': 'salesclerk'}, {'id': 3090, 'name': 'loser'}, {'id': 179430, 'name': 'aftercreditsstinger'}]"
  },
  {
    "id": 31915,
    "movie_id": 1587,
    "genres": "[{'id': 10749, 'name': 'Romance'}, {'id': 18, 'name': 'Drama'}]",
    "imdb_id": 108550,
    "overview": "Gilbert has to care for his brother Arnie and his obese mother, which gets in the way when love walks into his life.",
    "popularity": "10.3919",
    "score": 7.8,
    "title": "What's Eating Gilbert Grape (1993)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BY2EyZDlhNjItODYzNi00Mzc3LWJjOWUtMTViODU5MTExZWMyL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0",
    "keywords": "[{'id': 380, 'name': 'brother brother relationship'}, {'id': 791, 'name': 'mentally disabled'}, {'id': 2029, 'name': 'iowa'}, {'id': 4129, 'name': 'widow'}, {'id': 10041, 'name': 'dysfunctional family'}, {'id': 10183, 'name': 'independent film'}]"
  },
  {
    "id": 31931,
    "movie_id": 9495,
    "genres": "[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 109506,
    "overview": "Exactly one year after young rock guitarist Eric Draven and his fiancée are brutally killed by a ruthless gang of criminals, Draven -- watched over by a hypnotic crow -- returns from the grave to exact revenge.",
    "popularity": "15.799336",
    "score": 7.6,
    "title": "The Crow (1994)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BM2Y4ZGVhZjItNjU0OC00MDk1LWI4ZTktYTgwMWJkNDE5OTcxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0",
    "keywords": "[{'id': 3335, 'name': 'halloween'}, {'id': 11363, 'name': 'arson'}, {'id': 18021, 'name': 'detroit'}]"
  },
  {
    "id": 32023,
    "movie_id": 13815,
    "genres": "[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 109842,
    "overview": "Michael is a 12-year-old drug pusher who lives in a crowded house with his cousins and aunt. His father has become a street bum,but still meets with Fresh on occasion to play chess. Fresh is rather quiet in a crazy world. Fresh's sister is a junkie who sleeps with the dealers that Fresh sells for. As the story progresses Fresh realizes that he doesn't want to sell drugs anymore - he wants revenge.",
    "popularity": "3.970215",
    "score": 7.7,
    "title": "Fresh (1994)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzZjYjE3OTAtYjUzNi00NjA5LThkYzctYWJhZmM5MmNiYjQ3XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0",
    "keywords": "[{'id': 1601, 'name': 'war on drugs'}, {'id': 2149, 'name': 'drug traffic'}, {'id': 2231, 'name': 'drug dealer'}, {'id': 2235, 'name': 'drug mule'}, {'id': 5707, 'name': 'childhood trauma'}, {'id': 6691, 'name': 'drug scene'}, {'id': 6712, 'name': 'death of a child'}, {'id': 9748, 'name': 'revenge'}, {'id': 14964, 'name': 'drug'}, {'id': 15155, 'name': 'witness to murder'}, {'id': 34079, 'name': 'death'}]"
  },
  {
    "id": 32024,
    "movie_id": 5503,
    "genres": "[{'id': 12, 'name': 'Adventure'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}, {'id': 9648, 'name': 'Mystery'}]",
    "imdb_id": 106977,
    "overview": "Wrongfully accused of murdering his wife, Richard Kimble escapes from the law in an attempt to find her killer and clear his name. Pursuing him is a team of U.S. marshals led by Deputy Samuel Gerard, a determined detective who will not rest until Richard is captured. As Richard leads the team through a series of intricate chases, he discovers the secrets behind his wife's death and struggles to expose the killer before it is too late.",
    "popularity": "10.08937",
    "score": 7.8,
    "title": "The Fugitive (1993)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2OTkxNDA2OV5BMl5BanBnXkFtZTgwMzg3MjkyMTE@._V1_UX182_CR0",
    "keywords": "[{'id': 520, 'name': 'chicago'}, {'id': 797, 'name': 'showdown'}, {'id': 1568, 'name': 'undercover'}, {'id': 3262, 'name': 'surgeon'}, {'id': 3437, 'name': 'death sentence'}, {'id': 3440, 'name': 'doomed man'}, {'id': 3442, 'name': 'lethal injection'}, {'id': 3713, 'name': 'chase'}, {'id': 9714, 'name': 'remake'}, {'id': 10085, 'name': 'betrayal'}, {'id': 10562, 'name': 'on the run'}, {'id': 10663, 'name': 'train crash'}, {'id': 10685, 'name': 'escape'}, {'id': 10718, 'name': 'fugitive'}, {'id': 10988, 'name': 'based on tv series'}, {'id': 11207, 'name': 'u.s. marshal'}, {'id': 13005, 'name': 'doctor'}, {'id': 14601, 'name': 'explosion'}, {'id': 14903, 'name': 'home invasion'}, {'id': 18118, 'name': 'disguise'}, {'id': 173976, 'name': 'one armed man'}, {'id': 180172, 'name': 'framed for murder'}, {'id': 187844, 'name': 'flashback'}, {'id': 226376, 'name': 'corrupt cop'}, {'id': 226499, 'name': 'manhunt'}, {'id': 227824, 'name': 'bus accident'}, {'id': 227825, 'name': 'storm drain'}]"
  },
  {
    "id": 32035,
    "movie_id": 11934,
    "genres": "[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}]",
    "imdb_id": 110074,
    "overview": "A naive business graduate is installed as president of a manufacturing company as part of a stock scam.",
    "popularity": "7.550545",
    "score": 7.3,
    "title": "The Hudsucker Proxy (1994)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzNkYzI4ZTYtZjJlZC00ZTVjLTk2MDYtYWMwODA0NmFiYTIwXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0",
    "keywords": "[{'id': 236, 'name': 'suicide'}, {'id': 242, 'name': 'new york'}, {'id': 417, 'name': 'corruption'}, {'id': 736, 'name': 'journalist'}, {'id': 1436, 'name': 'inventor'}, {'id': 1568, 'name': 'undercover'}, {'id': 4290, 'name': 'toy'}, {'id': 4812, 'name': 'plan'}, {'id': 5306, 'name': 'boss'}, {'id': 5340, 'name': 'investigation'}, {'id': 6129, 'name': 'company'}, {'id': 6133, 'name': 'industry'}, {'id': 8508, 'name': 'party'}, {'id': 10594, 'name': 'money'}, {'id': 203525, 'name': 'board'}, {'id': 203528, 'name': 'stocks'}]"
  },
  {
    "id": 32038,
    "movie_id": 9386,
    "genres": "[{'id': 28, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}, {'id': 9648, 'name': 'Mystery'}]",
    "imdb_id": 107206,
    "overview": "Veteran Secret Service agent Frank Horrigan is a man haunted by his failure to save President Kennedy while serving protection detail in Dallas. Thirty years later, a man calling himself \"Booth\" threatens the life of the current President, forcing Horrigan to come back to protection detail to confront the ghosts from his past.",
    "popularity": "12.637158",
    "score": 7.2,
    "title": "In the Line of Fire (1993)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjdhYjRlMTgtNTMzOS00OTZlLWIxMjAtNjM4NGY0NGQxODM3XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0",
    "keywords": "[{'id': 591, 'name': 'cia'}, {'id': 782, 'name': 'assassin'}, {'id': 795, 'name': 'running'}, {'id': 833, 'name': 'white house'}, {'id': 840, 'name': 'usa president'}, {'id': 3088, 'name': 'bodyguard'}, {'id': 10333, 'name': 'stalking'}, {'id': 15134, 'name': 'election'}, {'id': 33632, 'name': 'apartment'}, {'id': 41249, 'name': 'secret service'}, {'id': 208633, 'name': 'secret service agent'}]"
  },
  {
    "id": 32067,
    "movie_id": 9300,
    "genres": "[{'id': 10749, 'name': 'Romance'}, {'id': 18, 'name': 'Drama'}, {'id': 14, 'name': 'Fantasy'}]",
    "imdb_id": 107756,
    "overview": "In 1600, nobleman Orlando inherits his parents' house, thanks to Queen Elizabeth I, who commands the young man to never change. After a disastrous affair with Russian princess Sasha, Orlando looks for solace in the arts before being appointed ambassador to Constantinople in 1700, where war is raging. One morning, Orlando is shocked to wake up as a woman and returns home, struggling as a female to retain her property as the centuries roll by.",
    "popularity": "3.800785",
    "score": 7.2,
    "title": "Orlando (1992)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYmY1OTA3MjAtYjQxOC00OTlkLWExZWQtMjc3ZjExOWFhM2UwXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_UX182_CR0",
    "keywords": "[{'id': 212, 'name': 'london england'}, {'id': 2011, 'name': 'queen'}, {'id': 7153, 'name': 'queen elizabeth i'}, {'id': 11402, 'name': 'androgyny'}, {'id': 11687, 'name': 'breaking the fourth wall'}, {'id': 177998, 'name': 'nobility'}, {'id': 187056, 'name': 'woman director'}, {'id': 190071, 'name': 'gender bender'}]"
  },
  {
    "id": 32068,
    "movie_id": 9559,
    "genres": "[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 107808,
    "overview": "A kidnapped boy strikes up a friendship with his captor: an escaped convict on the run from the law, headed by an honorable U.S. Marshal.",
    "popularity": "8.040589",
    "score": 7.5,
    "title": "A Perfect World (1993)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZjcyYmU1NzYtMmJiYy00NjJlLWE5ZjMtZWNkOWNjZmQ4MzIyXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_UX182_CR0",
    "keywords": "[{'id': 1562, 'name': 'hostage'}, {'id': 9777, 'name': 'escape from prison'}, {'id': 12414, 'name': 'escaped convict'}, {'id': 170865, 'name': 'child kidnapping'}, {'id': 177609, 'name': 'criminologist'}, {'id': 208992, 'name': '1960s'}]"
  },
  
  
  {
    "id": 32137,
    "movie_id": 812,
    "genres": "[{'id': 16, 'name': 'Animation'}, {'id': 10751, 'name': 'Family'}, {'id': 35, 'name': 'Comedy'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 103639,
    "overview": "Princess Jasmine grows tired of being forced to remain in the palace and she sneaks out into the marketplace  in disguise where she meets street-urchin Aladdin and the two fall in love, although she may only marry a prince. After being thrown in jail, Aladdin and becomes embroiled in a plot to find a mysterious lamp with which the evil Jafar hopes to rule the land.",
    "popularity": "16.357419",
    "score": 8,
    "title": "Aladdin (1992)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTI4ODQ1MzAzNV5BMl5BanBnXkFtZTgwMzU4NzMxMDE@._V1_UY268_CR9",
    "keywords": "[{'id': 2343, 'name': 'magic'}, {'id': 4344, 'name': 'musical'}, {'id': 6513, 'name': 'cartoon'}, {'id': 7376, 'name': 'princess'}, {'id': 9673, 'name': 'love'}, {'id': 10267, 'name': 'comedy'}, {'id': 10336, 'name': 'animation'}, {'id': 15149, 'name': 'monkey'}, {'id': 173259, 'name': 'arab'}, {'id': 179430, 'name': 'aftercreditsstinger'}, {'id': 190536, 'name': 'genie'}, {'id': 234183, 'name': 'animal sidekick'}]"
  },
  {
    "id": 32143,
    "movie_id": 408,
    "genres": "[{'id': 14, 'name': 'Fantasy'}, {'id': 16, 'name': 'Animation'}, {'id': 10751, 'name': 'Family'}]",
    "imdb_id": 29583,
    "overview": "A beautiful girl, Snow White, takes refuge in the forest in the house of seven dwarfs to hide from her stepmother, the wicked Queen. The Queen is jealous because she wants to be known as \"the fairest in the land,\" and Snow White's beauty surpasses her own.",
    "popularity": "16.263878",
    "score": 7.6,
    "title": "Snow White and the Seven Dwarfs (1937)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQwMzE2Mzc4M15BMl5BanBnXkFtZTcwMTE4NTc1Nw@@._V1_UX182_CR0",
    "keywords": "[{'id': 351, 'name': 'poison'}, {'id': 616, 'name': 'witch'}, {'id': 1412, 'name': 'becoming an adult'}, {'id': 1647, 'name': 'sadness'}, {'id': 2011, 'name': 'queen'}, {'id': 2013, 'name': 'attempted murder'}, {'id': 3737, 'name': 'dying and death'}, {'id': 3758, 'name': 'appearance'}, {'id': 7376, 'name': 'princess'}, {'id': 166625, 'name': 'candlelight vigil'}, {'id': 169341, 'name': 'snow white'}]"
  },
  {
    "id": 32194,
    "movie_id": 10363,
    "genres": "[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 54189,
    "overview": "Tom Ripley is a talented mimic, moocher, forger and all-around criminal improviser; but there's more to Tom Ripley than even he can guess.",
    "popularity": "3.804493",
    "score": 7.8,
    "title": "Purple Noon (1960)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjBlNTIwYWQtYjBmZC00YjhlLWFiMjktMDVjOTlkNmE5NDVhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR4",
    "keywords": "[{'id': 383, 'name': 'poker'}, {'id': 544, 'name': 'sailboat'}, {'id': 851, 'name': 'dual identity'}, {'id': 3180, 'name': 'sailing'}, {'id': 4812, 'name': 'plan'}, {'id': 6149, 'name': 'police'}, {'id': 9937, 'name': 'suspense'}, {'id': 33626, 'name': 'millionaire'}, {'id': 155440, 'name': 'hitchcockian'}, {'id': 155845, 'name': 'french noir'}, {'id': 189574, 'name': 'evil man'}, {'id': 209096, 'name': 'forger'}]"
  },
  {
    "id": 32245,
    "movie_id": 21588,
    "genres": "[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'name': 'Drama'}, {'id': 27, 'name': 'Horror'}, {'id': 35, 'name': 'Comedy'}]",
    "imdb_id": 109592,
    "overview": "A cemetery man has the unusual problem of the dead rising from the grave. Himself and his assistant must end these creatures' lives again after they are reborn. Everything is going well until \"She\" comes along and stirs things up a bit.",
    "popularity": "6.247819",
    "score": 7.3,
    "title": "Cemetery Man (1994)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMmFlMDBmNzEtM2QxNS00MzUyLTk1YTAtZTQ3ODM5YThlOTFhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR0",
    "keywords": "[{'id': 6255, 'name': 'insanity'}, {'id': 10327, 'name': 'undead'}, {'id': 11187, 'name': 'grim reaper'}, {'id': 12377, 'name': 'zombie'}, {'id': 162810, 'name': 'macabre'}, {'id': 207769, 'name': 'grotesque'}]"
  },
  {
    "id": 32360,
    "movie_id": 872,
    "genres": "[{'id': 35, 'name': 'Comedy'}, {'id': 10402, 'name': 'Music'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 45152,
    "overview": "In 1927 Hollywood, Don Lockwood and Lina Lamont are a famous on-screen romantic pair in silent movies, but Lina mistakes the on-screen romance for real love. When their latest film is transformed into a musical, Don has the perfect voice for the songs, but strident voice faces the studio to dub her voice. Aspiring actress, Kathy Selden is brought in and, while she is working on the movie, Don falls in love with her.",
    "popularity": "11.064858",
    "score": 8.3,
    "title": "Singin' in the Rain (1952)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZDRjNGViMjQtOThlMi00MTA3LThkYzQtNzJkYjBkMGE0YzE1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UY268_CR0",
    "keywords": "[{'id': 3177, 'name': 'fan'}, {'id': 3748, 'name': 'morning'}, {'id': 4344, 'name': 'musical'}, {'id': 6494, 'name': 'talkie'}, {'id': 9104, 'name': 'partner'}, {'id': 9732, 'name': 'movie in movie'}, {'id': 156028, 'name': 'broadway'}, {'id': 164090, 'name': 'audience'}, {'id': 164623, 'name': 'chorus girl'}, {'id': 164628, 'name': 'diction coach'}, {'id': 164636, 'name': 'pearl necklace'}, {'id': 164641, 'name': 'flapper'}]"
  },
  {
    "id": 32365,
    "movie_id": 567,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 47396,
    "overview": "Professional photographer L.B. \"Jeff\" Jeffries breaks his leg while getting an action shot at an auto race. Confined to his New York apartment, he spends his time looking out of the rear window observing the neighbors. He begins to suspect that a man across the courtyard may have murdered his wife. Jeff enlists the help of his high society fashion-consultant girlfriend Lisa Freemont and his visiting nurse Stella to investigate.",
    "popularity": "17.911314",
    "score": 8.5,
    "title": "Rear Window (1954)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR0",
    "keywords": "[{'id': 428, 'name': 'nurse'}, {'id': 1003, 'name': 'photographer'}, {'id': 2619, 'name': 'suspicion of murder'}, {'id': 5490, 'name': 'girlfriend'}, {'id': 10226, 'name': 'neighbor'}, {'id': 10332, 'name': 'salesman'}, {'id': 33632, 'name': 'apartment'}, {'id': 160967, 'name': 'convalescence'}, {'id': 178649, 'name': 'voyeurism'}, {'id': 236909, 'name': 'homebound'}]"
  }]

  module.exports = {dummy}